# Site settings
title: "Ting-Chou Lin's Homepage"
description: "Ting-Chou Lin, Software Development Engineer (MTS) @ Cerebras"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ting-Chou (James) Lin"
resume_title:                   "Software Development Engineer (MTS) @ Cerebras"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jameslin.cb@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "858-210-2645"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "858-210-2645 • jameslin.cb@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>As a highly motivated software engineer with a strong background in both computer science and electronics engineering, I have developed a diverse set of skills through my 3+ years of professional full-time experience in the industry. Throughout my career, I have had the opportunity to work with cutting-edge technologies and collaborate with cross-functional teams to deliver innovative solutions. I have experience in developing graph algorithms for accelerators, optimizing software runtime, and enabling GPT/BERT models on accelerators. My current research focus is on search and optimization as well as design automation.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_research:        true
resume_section_projects:        true
resume_section_skills:          true
resume_section_patents:         true
resume_section_publications:    true
# resume_section_recognition:     true

# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jamestclin"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ting-chou-james-lin/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://jamestclin.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Google Analytics
google_analytics: UA-162183542-1

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
